language: node_js
node_js:
  - "lts/*"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run service/spec/postman_echo.json
